name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./FluentFunCleanArchitecture
      run: chmod +x gradlew
      
    - name: Build with Gradle
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew build

    - name: Lint Checking
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew lint

    - name: Run test
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew test
