name: Basic Build and Test checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle


  check:
    needs: build
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      working-directory: ./FluentFunCleanArchitecture
      run: chmod +x ./gradlew
    
    - name: Gradle Check
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew check

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      working-directory: ./FluentFunCleanArchitecture
      run: chmod +x ./gradlew
      
    - name: Gradle Test
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew test

  assemble:
    needs: test
    name: Assemble
    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      working-directory: ./FluentFunCleanArchitecture
      run: chmod +x ./gradlew
      
    - name: Gradle Assemble
      working-directory: ./FluentFunCleanArchitecture
      run: ./gradlew assemble
