name: Basic Build and Test checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x FunCleanArchitecture/FluentFunCleanArchitecture/gradlew

  check:
    needs: build
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Gradle Check
      working-directory: FunCleanArchitecture/FluentFunCleanArchitecture
      run: ./gradlew check

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Gradle Test
      working-directory: FunCleanArchitecture/FluentFunCleanArchitecture
      run: ./gradlew test

  assemble:
    needs: test
    name: Assemble
    runs-on: ubuntu-latest

    steps:
    - name: Gradle Assemble
      working-directory: FunCleanArchitecture/FluentFunCleanArchitecture
      run: ./gradlew assemble
